#!/bin/bash

ffmpeg -f video4linux2 -input_format h264 -video_size 640x480 -framerate 30 -i /dev/video0 -vcodec copy -g 60 -f h264 tcp://:8080?listen=1

# ffmpeg -f v4l2 -i /dev/video0 -framerate 30 -vcodec libx264 -tune zerolatency -preset ultrafast -g 25 -b:v 900k -f h264 tcp://:8080?listen=1
